### ISSUE TITLE
instructions in the readme

### ISSUE THREAD

**Issue by codivist** [chrsm/league-oauth2-stripe#1]
This little package is great. 
It would be nice and allow others to add this in quickly if some instructions or some simple examples.

**Comment by chrsm** [comment]
Sure thing. The platform this was (quickly) written up for no longer uses Stripe Auth, but I'll dig into the git history and see how I set it up previously, and update the readme. :)

**Comment by chrsm** [comment]
Took a cursory glance at the past history and this example follows how it was used. Let me know if you have any other questions, and thank you for the issue.

**Comment by codivist** [comment]
cool, thank you!
